#!/bin/bash

echo "add demo web content..."
mkdir /var/www/demo && cat << EOF > /var/www/demo/index.html
<html>
<head>
  <title>01 Labs demo container file</title>
</head>
<body>
  <p> Welcome ${DEMO_USER:-user}, to infinity and beyond!
</body>
</html>
EOF

echo "update demo VirtualHost configuration to default site..."
cat << EOF >> /etc/apache2/sites-available/demo.conf
<VirtualHost *:80>
        ServerName demo.01labs.net
        ServerAdmin zer0ne.io.x@gmail.com
        DocumentRoot /var/www/demo
</VirtualHost>
EOF

echo "activate updated virtual host configuration..."
cd /etc/apache2/sites-available && a2ensite "demo.conf"
service apache2 start && service apache2 reload
echo "127.0.0.1 demo.01labs.net" >> /etc/hosts
