#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

keystore_dir="${KEYSTORE_DIR:-/root/.local/shared/openethereum/${CHAIN:-kovan}/keys}"
backup_path="${BACKUP_PATH:-/tmp/backups/wallet-backup.zip}"
backup_interval="${BACKUP_INTERVAL:-0 * * * *}" # @hourly by default
backup_cmd="openethereum-helper account backup-keystore $BACKUP_PASSWORD --keystore-dir $keystore_dir \
    --chain ${CHAIN:-kovan} --backup-path $backup_path"

mkdir -p $(dirname ${backup_path})
if [[ -n $AUTO_BACKUP_KEYSTORE ]]; then
    service cron start
	echo "${backup_interval} ${backup_cmd}" > /tmp/openethereum-cron
	crontab /tmp/openethereum-cron && rm /tmp/openethereum-cron
fi
